# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ceacdbcac5261dbf86ff027a4a8d72ef552299b0b1b90a0ee4877ee9033495b8d4cd89874bf7899ef6adaf78324aeb095cb9d64a7ff5d2d25f38d7eef8b610

test:
  secret_key_base: 3d1dbc0251dd6662a782f7e51ed966ebae6a910fe033ffc0c10da9e7fde54e8aa6a59805f5062aa6c700108ea576ade49d33cf1d926bda8e68fbb256212cb40c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
